-- ===================================================================
-- ECDAT Enterprise Cryptographic Database Schema (MySQL Workbench)
-- NTRO Problem Statement SIH26164
-- ===================================================================

CREATE DATABASE IF NOT EXISTS `ecdat_db` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `ecdat_db`;

-- 1. Table: Crypto Assets (CBOM Inventory)
CREATE TABLE IF NOT EXISTS `crypto_assets` (
    `id` VARCHAR(64) PRIMARY KEY,
    `name` VARCHAR(255) NOT NULL,
    `algorithm` VARCHAR(100) NOT NULL,
    `key_size` VARCHAR(50) NOT NULL,
    `category` VARCHAR(50) NOT NULL,
    `location` VARCHAR(255) NOT NULL,
    `repository` VARCHAR(255) NOT NULL,
    `line_numbers` VARCHAR(50),
    `risk_level` VARCHAR(20) NOT NULL,
    `migration_priority` VARCHAR(20) NOT NULL,
    `data_lifetime_years` INT NOT NULL,
    `migration_time_years` INT NOT NULL,
    `threat_timeline_years` INT NOT NULL,
    `is_violating_mosca` BOOLEAN NOT NULL,
    `hndl_vulnerability_level` VARCHAR(50) NOT NULL,
    `business_criticality` VARCHAR(50) NOT NULL,
    `service_id` VARCHAR(64) NOT NULL,
    `service_name` VARCHAR(255) NOT NULL,
    `service_type` VARCHAR(50) NOT NULL,
    `impacted_applications` TEXT,
    `sensitive_data_types` TEXT,
    `data_classification` VARCHAR(100),
    `annual_risk_exposure_usd` VARCHAR(50),
    `pqc_nist_standard` VARCHAR(255) NOT NULL,
    `pqc_algorithm_family` VARCHAR(100) NOT NULL,
    `pqc_recommended_action` TEXT,
    `pqc_migration_phase` VARCHAR(100),
    `pqc_effort_weeks` INT,
    `pqc_code_before` TEXT,
    `pqc_code_after` TEXT,
    `cyclonedx_ref` VARCHAR(100),
    `crypto_type` VARCHAR(50),
    `oid` VARCHAR(100),
    `nist_status` VARCHAR(50),
    `fips_status` VARCHAR(50),
    `quantum_security_bits` INT,
    `summary` TEXT,
    `quantum_attack_vector` TEXT,
    `detected_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 2. Table: Scan History Records
CREATE TABLE IF NOT EXISTS `scan_records` (
    `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
    `scan_target_type` VARCHAR(50) NOT NULL,
    `target_reference` VARCHAR(255) NOT NULL,
    `files_analyzed` INT NOT NULL,
    `dependencies_analyzed` INT NOT NULL,
    `certificates_discovered` INT NOT NULL,
    `crypto_assets_discovered` INT NOT NULL,
    `critical_vulnerabilities` INT NOT NULL,
    `status` VARCHAR(50) NOT NULL,
    `duration_ms` BIGINT NOT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 3. Table: Ingress Handshake Telemetry Logs
CREATE TABLE IF NOT EXISTS `ingress_logs` (
    `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
    `timestamp_str` VARCHAR(50) NOT NULL,
    `client_ip` VARCHAR(50) NOT NULL,
    `target_service` VARCHAR(255) NOT NULL,
    `cipher_suite` VARCHAR(255) NOT NULL,
    `protocol` VARCHAR(50) NOT NULL,
    `action` VARCHAR(50) NOT NULL,
    `latency_ms` DOUBLE NOT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ===================================================================
-- Initial Seed Data (6 Canonical Enterprise Primitives)
-- ===================================================================

INSERT INTO `crypto_assets` (
    `id`, `name`, `algorithm`, `key_size`, `category`, `location`, `repository`, `line_numbers`,
    `risk_level`, `migration_priority`, `data_lifetime_years`, `migration_time_years`, `threat_timeline_years`,
    `is_violating_mosca`, `hndl_vulnerability_level`, `business_criticality`, `service_id`, `service_name`,
    `service_type`, `impacted_applications`, `sensitive_data_types`, `data_classification`, `annual_risk_exposure_usd`,
    `pqc_nist_standard`, `pqc_algorithm_family`, `pqc_recommended_action`, `pqc_migration_phase`, `pqc_effort_weeks`,
    `pqc_code_before`, `pqc_code_after`, `cyclonedx_ref`, `crypto_type`, `oid`, `nist_status`, `fips_status`,
    `quantum_security_bits`, `summary`, `quantum_attack_vector`
) VALUES 
(
    'asset-rsa-2048',
    'RSA-2048 Authentication Keypair',
    'RSA',
    '2048-bit',
    'ASYMMETRIC',
    'services/auth/auth.py',
    'enterprise-core-monorepo',
    'L42-L89',
    'CRITICAL',
    'CRITICAL',
    7, 2, 6,
    TRUE,
    'IMMEDIATE',
    'MISSION_CRITICAL',
    'svc-auth-core',
    'Core Authentication Service',
    'AUTH',
    'Customer Web Portal, Mobile Banking App, Single Sign-On (SSO) Gateway',
    'User Passwords, Refresh Tokens, Admin Private Credentials',
    'SESSION_CREDENTIALS',
    '$14,200,000 / year',
    'FIPS 204 (ML-DSA-65) & Hybrid Dilithium',
    'LATTICE',
    'Replace RSA-2048 digital signatures with NIST FIPS 204 (ML-DSA-65). Implement hybrid signing (RSA + ML-DSA) during transition phase for backward compatibility.',
    'Phase 1 (Immediate - Q3 2026)',
    4,
    'from cryptography.hazmat.primitives.asymmetric import rsa\n\nprivate_key = rsa.generate_private_key(\n    public_exponent=65537,\n    key_size=2048\n)\nsignature = private_key.sign(payload, padding.PKCS1v15(), hashes.SHA256())',
    'from pqcrypto.sign import mldsa65\n\npublic_key, secret_key = mldsa65.generate_keypair()\nsignature = mldsa65.sign(secret_key, payload)\n# Verified with ML-DSA-65 (NIST FIPS 204 Standard)',
    'crypto-rsa-2048-auth',
    'algorithm',
    '1.2.840.113549.1.1.1',
    'PQC_TRANSITION_REQUIRED',
    'FIPS 140-2 Legacy',
    0,
    'Core enterprise auth tokens signed with RSA-2048. Vulnerable to Shor\'s algorithm.',
    'Shor\'s Algorithm factorizes RSA-2048 in polynomial time O((log N)^3).'
),
(
    'asset-ecdsa-p256',
    'ECDSA P-256 Edge TLS Certificate',
    'ECDSA',
    'secp256r1 (256-bit)',
    'ASYMMETRIC',
    'infra/certs/cert.pem',
    'enterprise-core-monorepo',
    'L1-L32',
    'HIGH',
    'HIGH',
    5, 2, 6,
    TRUE,
    'IMMEDIATE',
    'HIGH',
    'svc-edge-gateway',
    'API Edge Gateway',
    'GATEWAY',
    'Partner REST API, Public Microservices Gateway',
    'In-Transit API Payloads, Bearer Tokens',
    'FINANCIAL_RECORDS',
    '$8,700,000 / year',
    'FIPS 204 (ML-DSA-65) / Dual-Cert Architecture',
    'LATTICE',
    'Transition TLS edge leaf certificates from ECDSA P-256 to Dual-Certificate (ECDSA + ML-DSA) or FIPS 204 ML-DSA signatures.',
    'Phase 1 (Immediate - Q3 2026)',
    3,
    '# OpenSSL ECDSA Configuration\nssl_certificate /etc/ssl/ecdsa_secp256r1.crt;\nssl_certificate_key /etc/ssl/ecdsa_secp256r1.key;',
    '# NIST Post-Quantum Hybrid TLS Setup\nssl_certificate /etc/ssl/mldsa65_hybrid.crt;\nssl_certificate_key /etc/ssl/mldsa65_hybrid.key;\nssl_ecdh_curve X25519Kyber768Draft00:X25519:secp256r1;',
    'crypto-ecdsa-p256-edge',
    'certificate',
    '1.2.840.10045.2.1',
    'PQC_TRANSITION_REQUIRED',
    'FIPS 140-3 Validated',
    0,
    'Edge API Gateway uses ECDSA P-256 for TLS termination. Discrete log vulnerable to Shor\'s algorithm.',
    'Shor\'s Algorithm computes elliptic curve discrete logarithms in polynomial time.'
),
(
    'asset-aes-256',
    'AES-256-GCM Database Column Encryption',
    'AES-GCM',
    '256-bit',
    'SYMMETRIC',
    'services/payments/payment.py',
    'enterprise-core-monorepo',
    'L112-L148',
    'LOW',
    'LOW',
    3, 1, 6,
    FALSE,
    'SAFE',
    'MISSION_CRITICAL',
    'svc-payment-vault',
    'Payment Tokenization Vault',
    'PAYMENT',
    'Checkout Microservice, Billing Engine, Card Processing Pipeline',
    'Credit Card Primary Account Numbers (PAN), CVVs, Banking Account Details',
    'TOP_SECRET_PII',
    '$1,200,000 / year',
    'AES-256-GCM (Quantum Resistant - Retain)',
    'SYMMETRIC',
    'Maintain AES-256-GCM. AES with 256-bit key length provides 128 bits of post-quantum security against Grover\'s algorithm.',
    'Compliant (Maintain)',
    0,
    'from cryptography.hazmat.primitives.ciphers.aead import AESGCM\n\naesgcm = AESGCM(key_256)\nencrypted_pan = aesgcm.encrypt(nonce, raw_pan, None)',
    '# AES-256-GCM is Quantum-Safe against Grover\'s search!\n# 256-bit key provides 128-bit quantum security margin.\n# Retain current configuration with strict key rotation.',
    'crypto-aes-256-gcm-vault',
    'algorithm',
    '2.16.840.1.101.3.4.1.46',
    'QUANTUM_RESISTANT',
    'FIPS 140-3 Validated',
    128,
    'Cardholder data encrypted with AES-256-GCM. Resilient against quantum cryptanalysis.',
    'Grover\'s algorithm provides quadratic speedup, reducing 256-bit search to 128 quantum bits (still mathematically unbreakable).'
)
ON DUPLICATE KEY UPDATE `name`=VALUES(`name`);
